### PR TITLE
Commented out some lines to allow compiling of programs via makefile.

### PR DESCRIPTION
**Pull request by AndrewShultz**
Commented out lines were undefined functions or operators.

### CODE REVIEW

**Comment by ikrav** [comment]
Andrew, how is that was not a problem before? I certainly typed "make" in the current version and it went ahead and made the library.

**Comment by AndrewShultz** [comment]
Hi Ilya,

It's not the framework itself but rather programs that use the libReco.so.
Before the change it was only possible to use the framework via ROOT script
but now the exact same thing can be done via normal C++ program.

Andrew

**Comment by ikrav** [comment]
Ok, fine. What do you think about adding a comment before each set of 
commented-out lines to the tune of 
   // This method(s) was introduced but has never been implemented

Otherwise, code readers in several years will be wondering what those commented
out lines are doing there.

Ilya

**Comment by AndrewShultz** [comment]
Yeah, that's a good idea and I'll do that. I'll commit it and send a pull
request sometime soon.

Andrew

**Pull request merged**
